[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:127 There was an error managing chromedriver (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)); using driver found in the cache
[32mINFO    [0m root:test_bulkupload.py:35 ============logged in to corporate portal============